# Setup
title: fgfgdfgdf
paginate: 1
baseurl: ""

# Gems
plugins:
  - jekyll-gist
  - jekyll-paginate
  - jekyll-seo-tag


version: 3.0.0

# Navbar page list
nav:
  - title: Blog
    url: /all

  - title: About
    url: /about
